### PR TITLE
#11 Add class row to answer in question.pstpl

### PR DESCRIPTION
**Pull request by tammoterhark**
Need to add .row to answer, or else you will have to add this to each question view in order to keep good structure os rows and cols

### CODE REVIEW

**Comment by tammoterhark** [comment]
NO, sorry, this is not good. Let's discuss this first.

Sometimes inside the answers a col-xx-xx is used, sometimes it is not.

Adding class row to the question.pstpl will require that all answers have a col structure. Is that something we should wish?

Would it not be better that if a col-xx-xx structure is needed inside the question view, it should be wrapped in a <div class="row"> statement? We then solve this in the question view, not in question.pstpl. This could be a step on the way to make the template agnostic of the css framework that is used.

**Comment by Shnoulle** [comment]
I use clearfix more than row. 

Yes to be more framework agnostic in future release, but actually : if we don't use col-sm etc ... we can not do something good.

But good question for row or not inside answers view ......

**Comment by tammoterhark** [comment]
I propose to use row as a starter inside a question view only when needed.
Today I do now ork, Monday again. Other things to do today!

**Comment by Shnoulle** [comment]
Yes,
Some have already 
```
<li id="javatdbXXX'>
<label class='col-sm-6'>
<div  class='col-sm-6'>
</li>
```
Easy to add row. 

A question about : https://github.com/Shnoulle/LimeSurvey-Shnoulle/blob/answers_html/application/views/survey/questions/yesno/buttons/item.php#L14  (example : http://testing.sondages.pro/answershtml/alternate/awesome/index.php/84134 or http://testing.sondages.pro/answershtml/index.php/84134 ) i'm not sure about the col-sm/col-xs of the wrapper : maybe this must be a template.css issue here to fix the width. And not the views.

Another : what do you think of the fa icon : remove it or no ?

**Comment by tammoterhark** [comment]
Peter: can you give your view on this?

**Comment by Shnoulle** [comment]
@tammoterhark : use @PeterEmil  to have an easy way send an alert to the user :) . When you use the @ github show the participant list of the issue :)

**Comment by PeterEmil** [comment]
I'm not a fan of putting styling into the HTML. The fa-icon is biased towards Bootstrap which we use anyway, but to make all future-proof I would opt for removing them and putting it in the `.css` files. That way theme-development will get easier as well; then we can use other icon-systems as well.

**Comment by Shnoulle** [comment]
In fact : Bootsrap include glyphicon. I think icon is a great tool for Web Developement today. Make it easy to do "what we want" easily if we use it in good manner. ANd fa is included by default actually.

Your right, in replace of <i class='fa'> we can directly use css with before/after in the li or label or etc ....

I think this make it easy for user to have a good screen now, we have a tooll. And template admin can easily use a .fa{display:none} for example ;).

I update the Y/N to use check/ban icon. Seems OK, but have a way to update it in QuestionAttribute is a good idea.

But the primary question is : Did col-sm-X/col-xs-Y must be used by default. Except where we have a 'Answer width'/'Question width' attribute : here it's the only clean solution (excpet if we use another brid system for that (i like grillade for this : http://knacss.com/grillade/grillade.scss only grid ...)

**Comment by PeterEmil** [comment]
Cool. I like http://susy.oddbird.net but perhaps in the future we can choose which system we want for theming ;)

**Comment by PeterEmil** [comment]
Just quick question: when a theme-dev want to use another icon-system, what do you propose? Mapping onto `fa fa-[icon-name]`?

**Comment by Shnoulle** [comment]
Actually : no idea, no clean solution 

Future :  https://github.com/LimeSurvey/LimeSurvey/commit/178cb6f5401c9cdcd82f24a3e95c892a14bfacb3

**Comment by LouisGac** [comment]
removing the _fa-*_ classes to replace all of them by LimeSurvey classes implies to remap all of them to the font-awesome hexadecimal values. I did it for some of the icons of the admin interface, because in early developments it was faster to it like that for jQgrids rather than editing each one of them one by one to change their icon classes:
https://github.com/LimeSurvey/LimeSurvey/blob/master/styles/Sea_Green/css/fonts.css#L270-L358

It's a long and painful work, and each time you want to use a new font awesome icon you must remap it. It' nor really make easier to use different icon fonts. 

Eg:

Let say we have an icon "_user_". If we use font-awesome, we'll use a class like ""_fa-user_", displaying immediately the icon group. If we use a neutral LimeSurvey class like "_ls-icon-user_", we must first map it to the hexadecimal definition of _fa-user_ ([f007](http://fontawesome.io/icon/user/)), so for us, this solution take more time than the first one. 

If an third party developer want to use a different icon font than font-awesome, both solution are equivalent. Let's say he uses glyph-icon: in the first case, he will have to remap _fa-user_ to the hexadecimal value  _&#xE004_. In the second case, he will have to remap ls-icon-user to  _&#xE004_. Same amount of work. 

I perfectly understand that in a way, _ls-icon-user_ is still a cleaner solution, being "LimeSurvey" branded. The question is: **are you really sure you want to do this long and painful work right now? Do you have the time/money do that little improvement?** 

It's up to you to choose.

**Comment by Shnoulle** [comment]
Adding emoji icon support : https://github.com/marmelab/universal.css/issues/18#issue-156323476 ;)

**Comment by PeterEmil** [comment]
To remove the standard class-naming and to put it in `:before` is best practice. Or a system like `<i></i>` as hook for an icon, __without__ an specified icon-name. That way it is dead easy to change because all you have to change is one line in the css; the `content: xx` statement.

What I don't understand is that `fa fa-[icon-name]` is used with the default Bootstrap icon-font which is glyphicon, which needs `glyphicon [glyphicon-name]`. Seems to me mapping is already an issue.

Maybe this needs an issue of its own.

**Comment by LouisGac** [comment]
PeterEmil:

I agree it's a good practice, but it's a lot of work, for not a lot of improvement. 

If you use the native fa-*, you don't need to add the content:xx. If you want to change it, then you remap it with content: xx (one line in the css, the very same line you're speaking about. So like I just said before: it's the same amount of work if you want to change it, regardless of what class name you use. 

It's up to you (and Tammo) to decide if it's really necessary. Also, for frontend, maybe there are not so much icons. So it's less than one day of work, maybe be Tammo will be ok to pay for it, or Denis to take the time to do it. 

About current mapping:
FontAwesome is more into the Open Source mentality than Glyphicon. In BS2, fontAwesome was used by default. Since BS3, the BS team did a commercial agreement to push people to use Glyphicon. 

Currently, we use 3 icon fonts:
1. Glyphicon, for native bootstrap elements (Denis yet removed a lot of them by the past). 
2. A custom icomoon font, based on the native [LimeSurvey SVG](https://github.com/LimeSurvey/Original-art/tree/master/gringegreen). 
2. FontAwesome: whenever a LS native icon is not available.

**Comment by PeterEmil** [comment]
As we're working on refactoring the views where the icon-instances are declared I will create an separate issue and like to work on it, so the frontend will be clean and future proof.

@tammoterhark and I just had a lovely conversation and whipped out a concept.

We will keep the used fonts, of course. Than you can see that in the long run its easier to maintain and for easier for devs to insert & style icons.

**Comment by LouisGac** [comment]
Great. It's just a question of time and money. If you have the time and the money to do that kind of things: perfect.

**Comment by PeterEmil** [comment]
:)

**Comment by tammoterhark** [comment]
Peter has the time, I need to have the money... We looked at it and in 13 instances in the default template there was an icon used via fa-

**Comment by tammoterhark** [comment]
Peter will only do it for the default template, I leave it to you to do it for the others...

**Comment by LouisGac** [comment]
13 instances is very few, so it's ok. Did you check into the views? Maybe there are not so many neither....

**Comment by tammoterhark** [comment]
Sorry, I meant 13 instances in all /application/views/survey/* Did not look in the other views. Was that necessary?

**Comment by LouisGac** [comment]
well if only 13 instances in views, it can be done very fast, so not a problem at all.

**Comment by Shnoulle** [comment]
There are some place where we still have glyphion at public : the date question  type

For glyphicon : there are a bug report somewhere . Else it's a licencing issue https://creativecommons.org/licenses/by/3.0/ but need a link to the glyphicon website in all template, even if updated by user. Bootstrap have a specific licence about this : but at a time : we think we allow to not use bootstrap ....

**Pull request closed without merging**
