### PR TITLE
Clean up on template/views level

### PR DESCRIPTION
**Pull request by tammoterhark**
Denis, I deleted many col-xx-xx statements and made sure that the default template still works. Also deleted several div's and did some clean up on template.css and flat_and_modern.css. 

Also renamed several classes: naming is a mess. Used the following scheme: a wrapper is something that is around containers. A question has one question-wrapper and inside this wrapper there are several containers for separate functions.

Please review and feedback. Thanks!

### CODE REVIEW

**Comment by tammoterhark** [comment]
#25

**Comment by Shnoulle** [comment]
Tammo : please, next time : can you separate the Yes/No and the Increase Same decrease ?

One push for template (efault or other)
One for views : with same objective.

I know its' difficut, but you must create a fork for each :).

I  pull, fix the conflict (surely in views ? ) and push

**Comment by tammoterhark** [comment]
OK, but just for my understanding: separate pull request do not need separate fork? I can do this in separate branches on the same fork, can't I?

**Comment by Shnoulle** [comment]
Yes : same fork but different branch.

In fact : a fork can have 

- Different branch on same fork
- Follow different branch on other fork

For a quick example : 

- Fork limesurvey in github 
- Fork your fork on your computer : the first repository is origin
- Add the official limesurvey repo : git remote add official https:.....LimeSurvey/LimeSurvey
 - Add this repo : git remote add shnoulle https:.....Shnoulle/LimeSurvey-Shnoulle

After to get the remote repo update : 
- git fetch official
- you can checkout a specific branch git checkout answershtml for example

etc ...

BUT : you have surely a gui to do this :)

**Comment by tammoterhark** [comment]
Currently I do this on command line. Which gui to you use?

**Comment by Shnoulle** [comment]
Actually : https://git-scm.com/docs/git-gui included in my distro.

**Pull request merged**
